### ISSUE TITLE
make bageLabel hiden

### ISSUE THREAD

**Issue by WhereFindYouAgin** [mustafaibrahim989/MIBadgeButton#4]
how to make my badge label heden when my number is 0, thank you return me

**Comment by mustafaibrahim989** [comment]
This will be available in release 0.0.7. Just use `button.hideWhenZero = YES` 👍 

Thanks

**Comment by WhereFindYouAgin** [comment]
thank you very much ,keep in contact

**Comment by saintjab** [comment]
Sorry guys, button.hideWhenZero = YES is not working for me.
![img_0574](https://cloud.githubusercontent.com/assets/9318267/16561808/0facbb98-41f3-11e6-804e-acd2c8a96364.jpg)

**Comment by saintjab** [comment]
Found the solution :)

```
- (void) configureButton:(MIBadgeButton *) button withBadge:(NSString *) badgeString {
    button.hideWhenZero = YES;
    [button setTitleColor:HiHA forState:UIControlStateNormal];
    [button setBadgeEdgeInsets:UIEdgeInsetsMake(4, 0, 0, 8)];
    [button setBadgeString:badgeString];
    button.hideWhenZero = YES;// didn't work here
}
```

**Comment by WhereFindYouAgin** [comment]
its long time ago，so I used another API, but thank you ,and  I hope you make it more perfect.

**Comment by mustafaibrahim989** [comment]
so it works. I will fix the issue this 👍

**Comment by WhereFindYouAgin** [comment]
ok ,you are good guy, thank you
